version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - devops_dit_project

  sonarqube:
    image: sonarqube:lts
    privileged: true
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/sonarqube_logs
      - sonarqube_extensions:/opt/sonarqube/sonarqube_extensions
    networks:
      - devops_dit_project

  nexus:
    image: sonatype/nexus3
    privileged: true
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - devops_dit_project
  
networks:
  devops_dit_project:

volumes:
  jenkins_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  nexus_data:
