module.exports.prenoms = [
    'Mohamed',
    'Alioune',
    'Ibrahima',
    'Boubacar',
    'Babacar',
    'Bocar',
    'Moctar',
    'Cheikh Tidiane',
    'Pape Ibrahima',
    'Abdoulaye',
    'Saliou',
    'Mamadou',
    'Mbaye',
    'Amadou',
    'Bouna',
    'Sogui',
    'Fallou',
    'Tidiane',
    'Cheikh',
    'Omar',
    'Doudou',
    'Kader',
    'Alassane',
    'Souleymane',
    'Moustapha',
    'Sandiéry',
    'Arnaud',
    'Bruno',
    'Jack',
    'Frédéric',
    'Alexandre',
    'Aida',
    'Aissatou',
    'Mame Diarra',
    'Seynabou',
    'Awa',
    'Ndeye Fama',
    'Khady',
    'Diariatou',
    'Codou',
    'Marie',
    'Garmi',
    'Marème',
    'Rokhaya',
    'Dior',
    'Fatou',
    'Mame Fatou',
    'Anna',
    'Caroline',
    'Rose',
    'Eva',
    'Yakhara',
    'Isseu',
    'Sarah',
    'Soukeyna',
    'Aminata',
    'Abibatou',
    'Collé',
    'Coura',
    'Fatou Bintou',
    'Saly',
    'Massasi',
    'Lucie',
    'Bernadette',
    'Sokhna',
    'Alima'
]

module.exports.noms = [
    'Sylla',
    'Ndiaye',
    'Diop',
    'Camara',
    'Kâ',
    'Diallo',
    'Hanne',
    'Fall',
    'Cissé',
    'Diouf',
    'Kane',
    'Diakhaté',
    'Coulibaly',
    'Traoré',
    'Gaye',
    'Cissokho',
    'Dramé',
    'Bâ',
    'Ciss',
    'Mbacké',
    'Sy',
    'Ly',
    'Bousso',
    'Mbengue',
    'Diaby',
    'Top',
    'Doms',
    'Baly',
    'Thiandoum',
    'Tounkara',
    'Ngessan',
    'Dia'
]

module.exports.services = [
    'Médecine Générale',
    'Cancérologie',
    'Gynécologie',
    'Urologie',
    'Pédiatrie',
    'Cardiologie',
    'Néphrologie',
    'Neurologie',
    'Pneumologie',
    'Ophtalmologie',
    'Maternité',
    'ORL'
]

module.exports.prix = [5000, 7000, 10000, 12000, 15000, 18000, 20000]

module.exports.postes = [
    'Secrétaire d\'accueil',
    'Secrétaire de Service',
    'Facturier(e)',
    'Caissier(e)',
]

module.exports.symptomes = [
    'Fièvre élevée',
    'Frissons',
    'Malaise général',
    'Toux',
    'Fatigue',
    'Anorexie',
    'Crachat de pus',
    'Faiblesse musculaire',
    'Engourdissement du visage',
    'Engourdissement du visage, d\'un bras ou d\'une jambe',
    'Troubles visuels',
    'Difficultés de langage',
    'Pertes de sensibilité (contact, chaleur, douleur non perçus)',
    'Maux de têtes inhabituels',
    'Nausées',
    'Pertes d\'équilibre',
    'Chutes',
    'Vertiges',
    'Manque de coordination des mouvements',
    'Dysurie (difficultés pour uriner)',
    'Pollakiurie (mictions fréquentes et de faible abondance)',
    'Envies urgentes d\'uriner',
    'Dysfonction sexuelle',
    'Glande augmentée de volume, indolore, souple, régulière, élastique',
    'Pâleur de la peau et des muqueuses (conjonctives)',
    'Essoufflement lors des efforts (dyspnée)',
    'Tachycardie (accélération du rythme cardiaque)',
    'Fatigue persistante',
    'Maux de tête',
    'Difficultés de concentration',
    'Vertiges',
    'Bourdonnements d\'oreilles',
    'Baisse de désir sexuel',
    'Perte d\'appétit',
    'Vomissements',
    'Aménorrhée (arrêt des règles)',
    'Impuissance chez l\'homme',
    'Fièvre très modérée',
    'Douleurs abdominales',
    'Sensation de ballonnement',
    'Douleurs lombaires',
    'Difficulté à uriner',
    'Difficulté à marcher en raison d\'une douleur dans les jambes survenant à l\'effort',
    'Douleur vive en bas et à droite de l\'ombilic',
    'Vomissements discrets, alimentaires ou bilieux,',
    'Pouls accéléré',
    'Langue blanchâtre',
    'Constipation ',
    'Rougeurs',
    'Prurit',
    'Fièvre',
    'Éruption cutanée',
    'Douleurs musculaires',
    'Fatigue',
    'Diarrhée',
    'Apparition de sang dans les selles',
    'Présence de sang dans les urines',
    'Fibrose de la vessie et de l\'urètre',
    'Lésions génitales chez la femme',
    'Douleurs pendants les rapports sexuels',
    'Nodules dans la vulve',
    'Brûlures intenses à la miction',
    'Ecoulement purulent jaunâtre',
    'Pertes jaunâtres',
    'Rhume avec fébricule',
    'Petite fièvre',
    'Ecoulement nasal',
    'Toux sèche inconstante',
    'Difficultés respiratoires',
    'Pâleur et de cyanose',
    'Fièvre discrète ou modérée',
    'Toux grasse qui peut provoquer des vomissements',
    'Gonflement des jambes',
    'Gonflement des chevilles',
    'Gonflement des veines jugulaires au cou',
    'Ecoulement nasal',
    'Toux avec crachats mucopurulents',
    'Sifflement respiratoire',
    'Sensation de brûlure ou douleur d\'un côté de la gorge',
    'Impression d\'avoir une angine traînante',
    'Sensation permanente d\'avoir un corps étranger dans la gorge',
    'Douleur à une oreille',
    'Gêne ou difficulté à avaler ou à respirer',
    'Douleur quand on avale qui irradie vers l\'oreille',
    'Apparition d\'une boule (un ganglion) dans le cou ou sous l\'angle de la mâchoire',
    'Crachats sanglants',
    'Douleurs au niveau de l\'anus et du rectum',
    'Douleurs osseuses et/ou une altération de l\'état général',
    'Pertes de sang (métrorragies)',
    'Leucorrhées (pertes blanches) indolores',
    'Hémorragie utérine ( métrorragie ), isolée et spontanée, chez une femme qui n\'a plus ses règles',
    'Leucorrhées (pertes blanches) indolores',
    'Dysphonie progressive',
    'Dysphagie (difficulté pour avaler)',
    'Boule aux contours irréguliers',
    'Ganglions durs au niveau de l\'aisselle',
    'Apparition d\'une peau d\'orange, d\'une rondeur',
    'Mamelon rentrant',
    'Ecoulement par le mamelon',
    'Rougeur sur le mamelon',
    'Changements de la taille ou la forme du ou des seins',
    'Douleur osseuse',
    'Perte de poids',
    'Perte d’appétit',
    'Jaunisse',
    'Accumulation de liquide autour des poumons (épanchement pleural)',
    'Vision double',
    'Faiblesse musculaire',
    'Apparition de taches blanches sur la muqueuse de la bouche',
    'Présence de taches rouges sur la muqueuse de la bouche',
    'Mauvais hygiène ou état dentaire',
    'Discrète gêne lors de la mastication ou lors des mouvements de la langue',
    'Légers picotements accrus par les aliments acides ou épicés',
    'Lésion de la langue découverte par le patient lui-même ou le dentiste',
    'Démangeaisons du gland et du prépuce',
    'Infection de la vulve et du vagin (vulvo-vaginite) avec pertes blanches inodores',
    'Faiblesse musculaire',
    'Légère myopie',
    'Couleurs plus ternes',
    'Sensibilité à la lumière',
    'Pression ou tension autour de la tête irradaint jusqu\'au cou',
    'Vive douleur articulaire',
    'Articulations raides et un peu douloureuses',
    'Anorexie',
    'Nausées et/ou des régurgitations',
    'Lenteur de digestion',
    'Satiété précoce',
    'Asthénie physique et intellectuelle',
    'Troubles vasomoteurs cutanés',
    'Palpitations',
    'Céphalées',
    'Végétations vénériennes au niveau des organes génitaux',
    'Envie fréquente d\'uriner plusieurs fois par heure',
    'Douleur ou compression au niveau de la vessie, dans le bassin ou la partie inférieure de l\'abdomen',
    'Syndrome grippal avec une fièvre élevée',
    'Ralentissement du rythme cardiaque',
    'Hypotension',
    'Anorexie',
    'Douleurs derrière les yeux',
    'Éruption cutanée sur les joues',
    'Douleurs musculaires et courbatures diffuses',
    'Démarche raide et affectée',
    'Soif importante',
    'Envie d\'uriner très fréquente',
    'Asthénie',
    'Amaigrissement',
    'Douleurs abdominales',
    'Infections',
    'Eructations',
    'Hoquets',
    'Sensation de gonflement après les repas',
    'Satiété précoce',
    'Ballonnements au ventre',
    'Brûlures ou blocage derrière le sternum',
    'Renvois de liquide amer',
]

module.exports.excomps = [
    'Radiographie des poumons',
    'Radiographie du thorax',
    'Scanner',
    'Imagerie par résonance magnétique (IRM) cérébrale',
    'Palpation de l\'abdomen',
    'Toucher rectal pratiqué vessie vide',
    'Bilan sanguin',
    'Échographie',
    'Scanner abdominal',
    'Palpation douce et prudente',
    'Touchers pelviens (toucher rectal et toucher vaginal chez la femme)',
    'Radiographie de l\'abdomen',
    'Spirométrie',
    'Auscultation',
    'Infections vaginales et cervicales',
    'Nombre de grossesses supérieur à 1',
    'Précocité des rapports sexuels',
    'Changement fréquent de partenaires',
    'Frottis cervicovaginaux',
    'Colposcopie',
    'Examen au spéculum',
    'Homme',
    'Femme',
    'Test de Schiller',
    'Echographie du pelvis',
    'Biopsie',
    'Examen histologique',
    'Examen laryngologique direct',
    'Laryngoscopie',
    'Examen standard',
    'Toucher rectal',
    'Examen gynécologique',
    'Examen génital complet',
    'Examen endoscopique de l\'urètre',
    'Anuscopie',
    'Toucher rectal',

]

module.exports.predispos = [
   'Homme de plus de 50 ans',
   'Hypertendu',
   'En surpoids',
   'Diabétique',
   'Faible activité physique',
   'Entre 15 et 30 ans',
   'Tabagisme actif ou passif',
   'Antécédents d\'infections pulmonaires',
   'Vers 40 ans',
   'Expectorations (crachats)',
   'Essoufflements',
   'Rapports sexuels, bucco-génitaux, vaginaux ou anaux',
   'Nourrisson',
   'Pollution professionnelle',
   'Pollution atmosphérique',
   'Hypersensibilité allergique',
   'Infections respiratoires à répétition',
   'Homme',
   'Alcoolique',
   'Homme entre 50-70 ans',
   'Femme avant la ménopause',
   'Femme ménopausée',
   'Ménopause tardive',
   'Nulliparité',
   'Absence de rapport sexuels',
   'Grossesse',
   'Prise de pilule',
   'Période des règles',
   'Prise d\'antibiotiques, de corticoïdes',
   'Défenses immunitaires affaiblies',
   'Personnes de plus de 65 ans',
   'Vieillesse',
   'Stress',
   'Personnes de plus de 50 ans',
   'Hérédité',
   'Sédentarité',
   'Naissance de bébés faisant plus de 4 kilos',
   'Avant l\'âge de 30 ans',
]